# Generated by Django 5.0 on 2025-04-13 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次修改用户名时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='username_changes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='用户名修改次数'),
        ),
    ]
