# Generated by Django 5.0 on 2025-04-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_username_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to='backgrounds/', verbose_name='背景图片'),
        ),
    ]
