# Generated by Django 5.0 on 2025-04-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background',
            field=models.ImageField(blank=True, default='backgrounds/default-background.jpg', null=True, upload_to='backgrounds/', verbose_name='背景图片'),
        ),
    ]
